terminal:
  image: bdsmaneger/node_image:latest
  services:
    - docker:dind
  before_script:
    - apt update && apt install -y curl &> /dev/null
    - curl https://get.docker.com | bash -
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DEVELOP_WEBIDE: true
  script: sleep 80